name: Changelog Generation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script test
        run: pytest

      - name: Run changelog generator
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python src/main.py